//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.Communication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.Communication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailedToSendPacket.
        /// </summary>
        internal static string FailedToSendPacket {
            get {
                return ResourceManager.GetString("FailedToSendPacket", resourceCulture);
            }
        }

 /// <summary>
        ///   Looks up a localized string similar to Checksum size is invalid..
        /// </summary>
        internal static string ChecksumSizeIsInvalid {
            get {
                return ResourceManager.GetString("ChecksumSizeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client closes server..
        /// </summary>
        internal static string ClientClosesServer {
            get {
                return ResourceManager.GetString("ClientClosesServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client to not accept data: .
        /// </summary>
        internal static string ClientToNotAcceptData {
            get {
                return ResourceManager.GetString("ClientToNotAcceptData", resourceCulture);
            }
        }

 /// <summary>
        ///   Looks up a localized string similar to Connection not initialized..
        /// </summary>
        internal static string ConnectionNotInitialized {
            get {
                return ResourceManager.GetString("ConnectionNotInitialized", resourceCulture);
            }
        }
         /// <summary>
        ///   Looks up a localized string similar to Corrupted data..
        /// </summary>
        internal static string CorruptedData {
            get {
                return ResourceManager.GetString("CorruptedData", resourceCulture);
            }
        }
         /// <summary>
        ///   Looks up a localized string similar to Invalid BCD format: .
        /// </summary>
        internal static string InvalidBCDFormat {
            get {
                return ResourceManager.GetString("InvalidBCDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format..
        /// </summary>
        internal static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sender..
        /// </summary>
        internal static string InvalidSender {
            get {
                return ResourceManager.GetString("InvalidSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is old..
        /// </summary>
        internal static string IsOld {
            get {
                return ResourceManager.GetString("IsOld", resourceCulture);
            }
        } 

/// <summary>
        ///   Looks up a localized string similar to  ms..
        /// </summary>
        internal static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }

 /// <summary>
        ///   Looks up a localized string similar to Packet is old and send broadcast..
        /// </summary>
        internal static string PacketIsOldAndSendBroadcast {
            get {
                return ResourceManager.GetString("PacketIsOldAndSendBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet&apos;s byte order is not same as client&apos;s..
        /// </summary>
        internal static string PacketSByteOrderIsNotSameAsClientS {
            get {
                return ResourceManager.GetString("PacketSByteOrderIsNotSameAsClientS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet&apos;s wait time can&apos;t be Zero..
        /// </summary>
        internal static string PacketSWaitTimeCanTBeZero {
            get {
                return ResourceManager.GetString("PacketSWaitTimeCanTBeZero", resourceCulture);
            }
        }
         /// <summary>
        ///   Looks up a localized string similar to Received packet is not accepted..
        /// </summary>
        internal static string ReceivedPacketIsNotAccepted {
            get {
                return ResourceManager.GetString("ReceivedPacketIsNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply packet received in .
        /// </summary>
        internal static string ReplyPacketReceivedIn {
            get {
                return ResourceManager.GetString("ReplyPacketReceivedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to accept new client. Bop value is invalid..
        /// </summary>
        internal static string ServerFailedToAcceptNewClientBopValueIsInvalid {
            get {
                return ResourceManager.GetString("ServerFailedToAcceptNewClientBopValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to accept new client. ByteOrders are not same..
        /// </summary>
        internal static string ServerFailedToAcceptNewClientByteOrdersAreNotSame {
            get {
                return ResourceManager.GetString("ServerFailedToAcceptNewClientByteOrdersAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to accept new client. ChecksumSettings are not same..
        /// </summary>
        internal static string ServerFailedToAcceptNewClientChecksumSettingsAreNotSame {
            get {
                return ResourceManager.GetString("ServerFailedToAcceptNewClientChecksumSettingsAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to accept new client. Eop value is invalid..
        /// </summary>
        internal static string ServerFailedToAcceptNewClientEopValueIsInvalid {
            get {
                return ResourceManager.GetString("ServerFailedToAcceptNewClientEopValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to accept new client. MinimumSize value is invalid..
        /// </summary>
        internal static string ServerFailedToAcceptNewClientMinimumSizeValueIsInvalid {
            get {
                return ResourceManager.GetString("ServerFailedToAcceptNewClientMinimumSizeValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to accept new client. ParseReceivedPacket value is invalid..
        /// </summary>
        internal static string ServerFailedToAcceptNewClientParseReceivedPacketValueIsInvalid {
            get {
                return ResourceManager.GetString("ServerFailedToAcceptNewClientParseReceivedPacketValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not created. Call AssignMedia first..
        /// </summary>
        internal static string ServerNotCreatedCallAssignMediaFirst {
            get {
                return ResourceManager.GetString("ServerNotCreatedCallAssignMediaFirst", resourceCulture);
            }
        }

 /// <summary>
        ///   Looks up a localized string similar to Unknown media: .
        /// </summary>
        internal static string UnknownMedia {
            get {
                return ResourceManager.GetString("UnknownMedia", resourceCulture);
            }
        }
        
        
    }
}
